# ─── Dados Do Jogo ────────────────────────────────────────────────────────────

champions:
  - aatrox
  - ahri
  - akali
  - akshan
  - alistar
  - amumu
  - anivia
  - annie
  - aphelios
  - ashe
  - aurelionsol
  - azir
  - bard
  - belveth
  - blitzcrank
  - brand
  - braum
  - caitlyn
  - camille
  - cassiopeia
  - chogath
  - corki
  - darius
  - diana
  - drmundo
  - draven
  - ekko
  - elise
  - evelynn
  - ezreal
  - fiddlesticks
  - fiora
  - fizz
  - galio
  - gangplank
  - garen
  - gnar
  - gragas
  - graves
  - gwen
  - hecarim
  - heimerdinger
  - illaoi
  - irelia
  - ivern
  - janna
  - jarvaniv
  - jax
  - jayce
  - jhin
  - jinx
  - ksante
  - kaisa
  - kalista
  - karma
  - karthus
  - kassadin
  - katarina
  - kayle
  - kayn
  - kennen
  - khazix
  - kindred
  - kled
  - kogmaw
  - leblanc
  - leesin
  - leona
  - lillia
  - lissandra
  - lucian
  - lulu
  - lux
  - malphite
  - malzahar
  - maokai
  - masteryi
  - milio
  - missfortune
  - mordekaiser
  - morgana
  - nami
  - nasus
  - nautilus
  - neeko
  - nidalee
  - nilah
  - nocturne
  - nunu
  - olaf
  - orianna
  - ornn
  - pantheon
  - poppy
  - pyke
  - qiyana
  - quinn
  - rakan
  - rammus
  - reksai
  - rell
  - renata
  - renekton
  - rengar
  - riven
  - rumble
  - ryze
  - samira
  - sejuani
  - senna
  - seraphine
  - sett
  - shaco
  - shen
  - shyvana
  - singed
  - sion
  - sivir
  - skarner
  - sona
  - soraka
  - swain
  - sylas
  - syndra
  - tahmkench
  - taliyah
  - talon
  - taric
  - teemo
  - thresh
  - tristana
  - trundle
  - tryndamere
  - twistedfate
  - twitch
  - udyr
  - urgot
  - varus
  - vayne
  - veigar
  - velkoz
  - vex
  - vi
  - viego
  - viktor
  - vladimir
  - volibear
  - warwick
  - monkeyking
  - xayah
  - xerath
  - xinzhao
  - yasuo
  - yone
  - yorick
  - yuumi
  - zac
  - zed
  - zeri
  - ziggs
  - zilean
  - zoe
  - zyra

spells:
  flash: 10 #300
  curar: 240
  fantasma: 210
  teleporte: 360
  incendiar: 180
  purificar: 210
  barreira: 180

roles:
  - top
  - mid
  - jungle
  - support
  - adc

# ─── Dados Do Modelo ──────────────────────────────────────────────────────────

mistakes:
  counters:
    - country
    - counter
  adc:
    - dc
    - abc
  support:
    - suporte
  mid:
    - midi
  jungle:
    - jungler

# ─── Configurações Do Algoritmoo ──────────────────────────────────────────────

delay: 5